FROM php:8.2-apache

# install depedensi 
RUN apt-get update  && \
    apt-get install -y \
    libzip-dev\
    zip \
    libpq-dev

# enable a2enmod
RUN a2enmod rewrite

# install extension
RUN docker-php-ext-install pdo pdo_pgsql zip

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf



WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# RUN composer install

# RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
